CREATE TABLE 'trainingmodule' (
  'MODULE_ID' int(10) unsigned NOT NULL AUTO_INCREMENT,
  'MODULE_NAME' varchar(100) NOT NULL,
  'DURATION_IN_DAYS' int(10) unsigned NOT NULL,
  PRIMARY KEY ('MODULE_ID')
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;